# Generated by Django 5.2.4 on 2025-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
